version: "3.8"

services:
    app:
        build:
            context: .
        container_name: news-api-app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - laravel
        depends_on:
            - db
        env_file:
            - .env.docker

    web:
        image: nginx:alpine
        container_name: news-api-web
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: news-api-db
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: news_aggregator
            MYSQL_USER: user
            MYSQL_PASSWORD: root
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

networks:
    laravel:

volumes:
    dbdata:
